// @ts-nocheck
"use client";
import React, { useState, useEffect } from "react";

interface EmailApprovalArgs {
  recipient_name: string;
  recipient_email: string;
  conversation_summary: string;
  // Add other potential args if needed based on your tool definition
}

interface EmailApprovalComponentProps {
  args: EmailApprovalArgs;
  respond: (response: { accepted: boolean; message?: string; modified_summary?: string; recipient_email?: string }) => void;
  status: string; // Typically "executing" when waiting for response
}

const EmailApprovalComponent: React.FC<EmailApprovalComponentProps> = ({
  args,
  respond,
  status,
}) => {
  const [emailDetails, setEmailDetails] = useState({
    recipient_name: args?.recipient_name || "",
    recipient_email: args?.recipient_email || "",
    conversation_summary: args?.conversation_summary || "",
  });

  const [accepted, setAccepted] = useState<boolean | null>(null);

  // Update state whenever args change
  useEffect(() => {
    console.log('Args received:', args);
    if (args) {
      setEmailDetails({
        recipient_name: args.recipient_name || "",
        recipient_email: args.recipient_email || "",
        conversation_summary: args.conversation_summary || "",
      });
    }
  }, [args]);

  const handleInputChange = (field: keyof typeof emailDetails, value: string) => {
    setEmailDetails(prev => ({
      ...prev,
      [field]: value,
    }));
  };

  const handleApprove = async () => { // Make the function async
  if (respond) {
    setAccepted(true);

    // Prepare the payload for the SendGrid Cloud Function
    const emailPayload = {
      sender_email: "no-reply@disearch.ai", // Use the sender email from your agent's instructions
      sender_username: "SLAM",               // Use the sender name from your agent's instructions
      recipient_email: emailDetails.recipient_email,
      body: emailDetails.conversation_summary // Use the summary generated by the agent
    };
    console.log("email payload", emailPayload)

    let message = "";
    try {
      // Call the SendGrid Cloud Function
      const response = await fetch('https://sendgrid-email-359065791766.us-central1.run.app', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(emailPayload)
      });

      if (response.ok) { // Check if status code is 2xx (e.g., 200)
        message = `Email successfully sent to ${emailDetails.recipient_email}`;
        console.log("Email sent successfully");
      } else {
        // Handle non-2xx status codes
        console.error("Failed to send email. Status:", response.status);
        message = `Failed to send email to ${emailDetails.recipient_email}. Status: ${response.status}`;
        // Optionally, check response.text() for more details from the CF
        // const errorText = await response.text();
        // console.error("Error details:", errorText);
      }
    } catch (error) {
      // Handle network errors or other exceptions during the fetch
      console.error("Error sending email:", error);
      message = `Failed to send email to ${emailDetails.recipient_email}. Network error occurred.`;
    }

    // Respond to the agent with the outcome
    respond({
      accepted: true,
      message: message, // Use the dynamic message based on CF response
    //   modified_summary: emailDetails.conversation_summary, // Pass back the summary if needed
    //   recipient_email: emailDetails.recipient_email
    });
  }
};


  const handleReject = () => {
    if (respond) {
      setAccepted(false);
      respond({ 
        accepted: false,
        message: "Email cancelled by user"
      });
    }
  };

  // Early return with better debugging
  if (!args) {
    console.log('No args provided to EmailApprovalComponent');
    return <div className="p-4 text-red-500">No email data provided</div>;
  }

  console.log('Rendering with emailDetails:', emailDetails);

  return (
    <div className="flex flex-col gap-4 w-full max-w-2xl bg-white rounded-lg p-6 mb-4 border border-gray-200 shadow-sm">
      <div className="text-black space-y-4">
        <h2 className="text-xl font-bold mb-4">📧 Review & Send Email Summary</h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">From</label>
            <div className="px-3 py-2 bg-gray-100 border border-gray-300 rounded-md">
              no-reply@slamsports.ai (Slam)
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              To: {emailDetails.recipient_name || 'Unknown Recipient'}
            </label>
            <input
              type="email"
              value={emailDetails.recipient_email}
              onChange={(e) => handleInputChange("recipient_email", e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
              placeholder="Enter recipient email"
              disabled={accepted !== null}
            />
          </div>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Conversation Summary</label>
          <textarea
            value={emailDetails.conversation_summary}
            onChange={(e) => handleInputChange("conversation_summary", e.target.value)}
            rows={8}
            className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 font-mono text-sm"
            placeholder="Review and edit the conversation summary..."
            disabled={accepted !== null}
          />
        </div>

        {/* Debug info - remove in production */}
        {/* <div className="text-xs text-gray-500 bg-gray-50 p-2 rounded">
          <strong>Debug:</strong> Status: {status}, Args: {JSON.stringify(args, null, 2)}
        </div> */}
      </div>

      {/* Action Buttons */}
      {accepted === null && (
        <div className="flex justify-end space-x-4 pt-4">
          <button
            className={`px-4 py-2 rounded ${
              status === "executing"
                ? "bg-gray-200 text-gray-800 hover:bg-gray-300 cursor-pointer"
                : "bg-gray-100 text-gray-400 cursor-not-allowed"
            }`}
            // disabled={status !== "executing"}
            onClick={handleReject}
          >
            Cancel
          </button>
          <button
            className={`px-4 py-2 rounded text-white ${
              status === "executing"
                ? "bg-blue-600 hover:bg-blue-700 cursor-pointer"
                : "bg-blue-400 cursor-not-allowed"
            }`}
            // disabled={status !== "executing" || !emailDetails.recipient_email}
            onClick={handleApprove}
          >
            Send Email
          </button>
        </div>
      )}

      {/* Status Feedback */}
      {accepted !== null && (
        <div className="flex justify-end">
          <div
            className={`px-4 py-2 rounded inline-block ${
              accepted
                ? "bg-green-100 text-green-800"
                : "bg-red-100 text-red-800"
            }`}
          >
            {accepted ? "✓ Approved & Sending" : "✗ Cancelled"}
          </div>
        </div>
      )}
    </div>
  );
};

export default EmailApprovalComponent;