PENN_STATE_OUTPUT = [
[
  {
    "Name": "Mason Blackwood",
    "value_scoring": 17.7,
    "value_reb_pct": 7.4,
    "value_three_pct": 49,
    "value_blk_pct": None,
    "value_STL": None,
    "value_D": None,
    "players": "Player is a four-star small forward from New Hampton Prep, name not mentioned",
    "color_three_pct": "Green (very strong)",
    "color_scoring": "Green (very strong)",
    "color_reb_pct": "Green (very strong)",
    "color_O": "Green",
    "color_Diff": "Green",
    "value_PF": None,
    "value_two_pct": None,
    "value_ft_pct": None,
    "value_assist_rate": None,
    "value_TO": None,
    "value_playmaking": None,
    "value_oreb_pct": None,
    "value_dreb_pct": None,
    "color_two_pct": None,
    "color_ft_pct": None,
    "color_assist_rate": None,
    "color_TO": None,
    "color_playmaking": None,
    "color_oreb_pct": None,
    "color_dreb_pct": None,
    "color_blk_pct": None,
    "color_STL": None,
    "color_PF": None,
    "color_D": "Green (defensive accolades)"
  },
  {
    "Name": "Ivan Jurić",
    "value_scoring": 14,
    "value_reb_pct": 9.8,
    "value_three_pct": 43,
    "value_blk_pct": 0.6,
    "value_STL": 0.8,
    "value_D": None,
    "players": "Three-star center from Croatia, Sunrise Christian/BC Dubrava",
    "color_three_pct": "Green",
    "color_scoring": "Green",
    "color_reb_pct": "Green",
    "color_O": "Green",
    "color_Diff": "Green",
    "value_PF": 58.6,
    "value_two_pct": 69,
    "value_ft_pct": 1.6,
    "value_assist_rate": None,
    "value_TO": None,
    "value_playmaking": None,
    "value_oreb_pct": None,
    "value_dreb_pct": None,
    "color_two_pct": "Green",
    "color_ft_pct": "Yellow",
    "color_assist_rate": "Yellow",
    "color_TO": None,
    "color_playmaking": None,
    "color_oreb_pct": "Yellow",
    "color_dreb_pct": "Yellow",
    "color_blk_pct": None,
    "color_STL": "Green",
    "color_PF": None,
    "color_D": None
  },
  {
    "Name": "Kayden Mingo",
    "value_scoring": 13.6,
    "value_reb_pct": 5.4,
    "value_three_pct": 44,
    "value_blk_pct": None,
    "value_STL": 1.9,
    "value_D": None,
    "players": "Consensus top-40 combo guard, highest-ranked recruit in Penn State history",
    "color_three_pct": "Green",
    "color_scoring": "Green",
    "color_reb_pct": "Green",
    "color_O": "Green",
    "color_Diff": "Green",
    "value_PF": 54,
    "value_two_pct": 78,
    "value_ft_pct": 4.1,
    "value_assist_rate": None,
    "value_TO": None,
    "value_playmaking": None,
    "value_oreb_pct": None,
    "value_dreb_pct": None,
    "color_two_pct": "Green",
    "color_ft_pct": "Green",
    "color_assist_rate": "Green",
    "color_TO": None,
    "color_playmaking": None,
    "color_oreb_pct": "Green",
    "color_dreb_pct": "Green",
    "color_blk_pct": None,
    "color_STL": "Green",
    "color_PF": None,
    "color_D": None
  },
  {
    "Name": "Melih Tunca",
    "value_scoring": 6.7,
    "value_reb_pct": 1.1,
    "value_three_pct": 47.5,
    "value_blk_pct": None,
    "value_STL": None,
    "value_D": None,
    "players": "Young Turkish guard, 2024–25 TBL Young Player of the Year (Turk Telekom)",
    "color_three_pct": "Green",
    "color_scoring": "Yellow",
    "color_reb_pct": "Red",
    "color_O": "Green",
    "color_Diff": "Green",
    "value_PF": 55,
    "value_two_pct": 96.4,
    "value_ft_pct": 2.2,
    "value_assist_rate": None,
    "value_TO": None,
    "value_playmaking": None,
    "value_oreb_pct": None,
    "value_dreb_pct": None,
    "color_two_pct": "Green",
    "color_ft_pct": "Green",
    "color_assist_rate": "Yellow",
    "color_TO": None,
    "color_playmaking": None,
    "color_oreb_pct": "Green",
    "color_dreb_pct": None,
    "color_blk_pct": "Yellow",
    "color_STL": None,
    "color_PF": None,
    "color_D": None
  },
  {
    "Name": "Reggie Grodin",
    "value_scoring": 12,
    "value_reb_pct": 6.6,
    "value_three_pct": 41,
    "value_blk_pct": None,
    "value_STL": 2.5,
    "value_D": None,
    "players": "Player from Newman School, NEPSAC AAA Champion 2025",
    "color_three_pct": "Green",
    "color_scoring": "Green",
    "color_reb_pct": "Green",
    "color_O": "Green",
    "color_Diff": "Green",
    "value_PF": 68,
    "value_two_pct": None,
    "value_ft_pct": 4.2,
    "value_assist_rate": 3.1,
    "value_TO": None,
    "value_playmaking": None,
    "value_oreb_pct": None,
    "value_dreb_pct": None,
    "color_two_pct": "Green",
    "color_ft_pct": None,
    "color_assist_rate": "Green",
    "color_TO": None,
    "color_playmaking": "Green",
    "color_oreb_pct": None,
    "color_dreb_pct": "Green",
    "color_blk_pct": None,
    "color_STL": "Green",
    "color_PF": None,
    "color_D": "Yellow"
  },
  {
    "Name": "Tibor Mirtič",
    "value_scoring": 11.5,
    "value_reb_pct": 4.1,
    "value_three_pct": 44.4,
    "value_blk_pct": None,
    "value_STL": None,
    "value_D": None,
    "players": "Slovenian forward, Krka Novo Mesto (ABA & Liga OTP), FIBA EuroBasket Qualifier",
    "color_three_pct": "Green",
    "color_scoring": "Green",
    "color_reb_pct": "Green",
    "color_O": "Green",
    "color_Diff": "Green",
    "value_PF": 66.2,
    "value_two_pct": None,
    "value_ft_pct": 1.9,
    "value_assist_rate": None,
    "value_TO": None,
    "value_playmaking": None,
    "value_oreb_pct": None,
    "value_dreb_pct": None,
    "color_two_pct": "Green",
    "color_ft_pct": None,
    "color_assist_rate": "Green",
    "color_TO": None,
    "color_playmaking": None,
    "color_oreb_pct": "Green",
    "color_dreb_pct": None,
    "color_blk_pct": "Green",
    "color_STL": None,
    "color_PF": None,
    "color_D": None
  },
  {
    "Name": "Justin Houser",
    "value_scoring": 7.8,
    "value_reb_pct": None,
    "value_three_pct": 37,
    "value_blk_pct": 1.1,
    "value_STL": None,
    "value_D": None,
    "players": "[Redacted Player Name]",
    "color_three_pct": "#66ccff",
    "color_scoring": "#99ccff",
    "color_reb_pct": "#99ccff",
    "color_O": None,
    "color_Diff": None,
    "value_PF": 1.5,
    "value_two_pct": None,
    "value_ft_pct": 78,
    "value_assist_rate": None,
    "value_TO": 1.1,
    "value_playmaking": None,
    "value_oreb_pct": None,
    "value_dreb_pct": None,
    "color_two_pct": "#ccffcc",
    "color_ft_pct": "#66ffcc",
    "color_assist_rate": None,
    "color_TO": None,
    "color_playmaking": "#66ffcc",
    "color_oreb_pct": None,
    "color_dreb_pct": "#ffcc66",
    "color_blk_pct": None,
    "color_STL": "#ccff66",
    "color_PF": None,
    "color_D": None
  },
  {
    "Name": "Chris Lotito",
    "value_scoring": None,
    "value_reb_pct": None,
    "value_three_pct": None,
    "value_blk_pct": None,
    "value_STL": None,
    "value_D": None,
    "players": None,
    "color_three_pct": None,
    "color_scoring": None,
    "color_reb_pct": None,
    "color_O": None,
    "color_Diff": None,
    "value_PF": None,
    "value_two_pct": None,
    "value_ft_pct": None,
    "value_assist_rate": None,
    "value_TO": None,
    "value_playmaking": None,
    "value_oreb_pct": None,
    "value_dreb_pct": None,
    "color_two_pct": None,
    "color_ft_pct": None,
    "color_assist_rate": None,
    "color_TO": None,
    "color_playmaking": None,
    "color_oreb_pct": None,
    "color_dreb_pct": None,
    "color_blk_pct": None,
    "color_STL": None,
    "color_PF": None,
    "color_D": None
  }
]
]